In [5]:
import pandas as pd

In [6]:
from sklearn import svm,datasets

In [7]:
iris=datasets.load_iris()

In [8]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [9]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
df["target"]=iris.target

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"]],df["target"],test_size=0.3)

In [14]:
from sklearn.svm import SVC
model=SVC(kernel="rbf",C=30,gamma="auto")
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8888888888888888

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(SVC(kernel="linear",C=10),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [17]:
cross_val_score(SVC(kernel="linear",C=20),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [20]:
from sklearn import tree

In [21]:
cross_val_score(tree.DecisionTreeClassifier(),iris.data,iris.target,cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

## As we clearly see that cal_val_score is used to find the score for different training and testing data but we want to change the perameter of model then we need to change mannually this will become frustrating

In [22]:
import numpy as np
kernals=['rbf','linear']
C=[1,10,20]
avg_scores={}
for kval in kernels:
    for cval in C:
        cv_score=cross_val_score(SVC(kernel=kval,C=cval,gamma="auto"),iris.data,iris.target,cv=5)
        avg_scores[kval + "_" + str(cval)]=np.average(cv_score)

NameError: name 'kernels' is not defined

In [ ]:
avg_scores

## By GridSearchCV we can clearly see that we can pass different perameter and check the best model

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
clf=GridSearchCV(svm.SVC(),{
    'C':[1,10,20],
    'kernel':["rbf","linear"]
},cv=5,return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_

## This data is not in readable form so we need to convert it into DataFrame

In [ ]:
df=pd.DataFrame(clf.cv_results_)

In [23]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [24]:
clf.best_score_

NameError: name 'clf' is not defined

In [25]:
clf.best_params_

NameError: name 'clf' is not defined

## Now we can Same do with with random selection of paramters because executing all the parameters permutation is too much time consumming

In [26]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(SVC(gamma='auto'),{
    "C":[1,10,20],
    "kernel":['rbf','linear']
},cv=5,return_train_score=False,n_iter=2)
rs.fit(iris.data,iris.target)
pd.DataFrame(rs.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.001999      0.000002         0.000800         0.00040       linear   
1       0.001999      0.000894         0.001599         0.00049          rbf   

  param_C                         params  split0_test_score  \
0      10  {'kernel': 'linear', 'C': 10}           1.000000   
1      10     {'kernel': 'rbf', 'C': 10}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.900000           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.973333        0.038873                2  
1         0.980000        0.016330                1

In [27]:
rs.best_params_

{'kernel': 'rbf', 'C': 10}

In [28]:
rs.best_score_

0.9800000000000001

In [29]:
from sklearn.linear_model import LogisticRegression

## Now this we can do with all the algo find the best from them

In [30]:
model_params={
    'svm':{
        'model':SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}

In [35]:
model_params.items()

dict_items([('svm', {'model': SVC(gamma='auto'), 'params': {'C': [1, 10, 20], 'kernel': ['rbf', 'linear']}}), ('random_forest', {'model': RandomForestClassifier(), 'params': {'n_estimators': [1, 5, 10]}}), ('logistic_regression', {'model': LogisticRegression(solver='liblinear'), 'params': {'C': [1, 5, 10]}})])

In [78]:
scores=[]
for model_name,mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

In [80]:
df=pd.DataFrame(scores,columns=["model","best_score","best_params"])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.966667        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}